version: "3.9"

services:
  db:
    image: postgres:16
    container_name: authservice-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  authservice:
    build: .
    container_name: authservice-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://authuser:authpassword@db:5432/authdb
      - JWT_SECRET_KEY=5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=120
      - COOKIE_SECURE="False"
    ports:
      - "8000:8000"

volumes:
  postgres_data: