networks:
  sistema-distribuido:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    container_name: gestiondb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres # Default database, script will connect to this
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./backend/authservice/db/schema.sql:/schemas/auth_schema.sql
      - ./backend/inventoryservice/db/schema.sql:/schemas/inventory_schema.sql
      - ./backend/productservice/db/schema.sql:/schemas/products_schema.sql
      - ./backend/ordersservice/db/schema.sql:/schemas/orders_schema.sql
    ports:
      - "5432:5432"
    networks:
      - sistema-distribuido
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s

  authservice:
    build:
      context: ./backend/authservice
      dockerfile: Dockerfile
    container_name: authservice
    env_file: ./backend/authservice/.env
    environment:
      DATABASE_URL: "postgresql://user:password@db/auth_db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - sistema-distribuido

  inventoryservice:
    build:
      context: ./backend/inventoryservice
      dockerfile: Dockerfile
    container_name: inventoryservice
    env_file: ./backend/inventoryservice/.env
    environment:
      DATABASE_URL: "postgres://user:password@db/inventory_db"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:3000"
    networks:
      - sistema-distribuido

  productservice:
    build:
      context: ./backend/productservice
      dockerfile: Dockerfile
    container_name: productservice
    env_file: ./backend/productservice/.env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: products_db
      DB_USERNAME: user
      DB_PASSWORD: password
      JWT_SECRET: 5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
      JWT_SECRET_KEY: 5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
      JWT_ALGORITHM: HS256
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8003:80"
    networks:
      - sistema-distribuido
  ordersservice:
    build: ./backend/ordersservice
    container_name: ordersservice
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/orders_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - JWT_SECRET=5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
      - JWT_SECRET_KEY=5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema-distribuido

  notificationsservice:
    build:
      context: ./backend/notificationsservice
      dockerfile: Dockerfile
    container_name: notificationsservice
    env_file: ./backend/notificationsservice/.env
    environment:
      PORT: 8000
      JWT_SECRET_KEY: 5da4065109ac40d49a724461fcde8c0f5f233275b72eed2229a9af2ac2300155
    ports:
      - "8004:8000"
    networks:
      - sistema-distribuido

  paymentservice:
    build:
      context: ./backend/paymentservice
      dockerfile: Dockerfile
    container_name: paymentservice
    env_file: ./backend/paymentservice/.env
    ports:
      - "3005:3005"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema-distribuido

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: on-failure:5
    ports:
      - "3000:80"
    depends_on:
      - authservice
      - inventoryservice
      - productservice
    networks:
      - sistema-distribuido

volumes:
  postgres_data:
