version: '3.8'

services:
  app:
    build: .
    ports:
      - "0049:80" # Para entrar a la aplicacion, usar 0049
    volumes:
      - .:/var/www/html # NO MODIFICAR ES PARA QUE LA SINCRONIZACION EN RT
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # Aumentar limite de subida para imagenes pesadas o mayores
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ultimaCena
    ports:
      - "5433:5432"