services:
  db:
    image: postgres:15-alpine
    container_name: payments_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payments-network

  app:
    build: .
    container_name: payments_service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=payments_db
      - DB_PORT=5432
      - JWT_SECRET=paymentservice-secret-key
    depends_on:
      - db
    networks:
      - payments-network

volumes:
  postgres_data:

networks:
  payments-network:
    driver: bridge